import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "./ConvexClientProvider";

const SNPro = localFont({
  src: "./fonts/SNPro-Regular.woff",
  variable: "--font-snpro",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider dynamic>
      <ConvexClientProvider>
        <html lang="en">
          <body className={`${SNPro.variable} font-snpro antialiased`}>
            <main>{children}</main>
          </body>
        </html>
      </ConvexClientProvider>
    </ClerkProvider>
  );
}
